### ISSUE TITLE
[FEA] SID Viz Folder

### ISSUE THREAD

**Issue by jarmak-nv** [nv-morpheus/morpheus-visualizations#3]
Bring the SID visualizations into its own folder.

**Comment by mdemoret-nv** [comment]
The plan for this is:

1. Make a multi-root VS Code workspace folder (See node-rapids layout)
2. Migrate entire existing repo into a SID folder
3. Add new folder for DFP and others
4. Downstream projects should make one submodule to this repo, then make symlinks to the desired folder as needed
